describe('Fault Log', () => {
  it('logs a new fault', () => {
    cy.submit()
    cy.contains('Log a fault').click()
    cy.get('input[name="reg"]')
    .type('AB123ABC')
    .should('have.value', 'AB123ABC')
    cy.get('input[name="make"]')
    .type('Ford')
    .should('have.value', 'Ford')
    cy.get('input[name="model"]')
    .type('Ranger')
    .should('have.value', 'Ranger')
    cy.contains('Submit').click()
    cy.get('p').contains('Thank you for submitting a new fault record.')
    cy.get('p').contains('Please click the button below to view the record')
    cy.contains('View').click()
  })
})